- name: Reload Firewalld
  systemd:
    name: firewalld
    state: restarted
  when: ansible_distribution == "CentOS"

- name: restart_apache
  tags: apache, httpd
  service:
    name: "{{ apache_service }}"
    state: restarted