- name: install unzip
  package:
    name: unzip

- name: install terrafrom
  unarchive:
    src: https://releases.hashicorp.com/terraform/1.7.4/terraform_1.7.4_linux_amd64.zip
    dest: /usr/local/bin
    remote_src: yes
    owner: root
    group: root
    mode: 0755
